// DEV-TOOLS:START
import { windowManager } from "../core/WindowManager.js";
import { DevDialogueEditorTab } from "./DevDialogueEditorTab.js";

import { CUSTOM_WIDGET_TYPES, createCustomEventBlueprint, createCustomWindowDraft, validateCustomWindow } from "./CustomWindowSchema.js";
import { launchCustomWindowApp } from "../apps/CustomWindowApp.js";

const clone = (value) => JSON.parse(JSON.stringify(value));
const esc = (value) => String(value ?? "").replace(/[&<>\"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char]));
const uid = (prefix) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
function newWidget(type = "label") { return { id: uid(type), type, x: 24, y: 24, width: type === "label" ? 160 : 180, height: type === "textarea" ? 70 : 30, text: CUSTOM_WIDGET_TYPES[type] }; }

/** Layout/property editor only. Blueprint editing is delegated to DevDialogueEditorTab. */
export class DevCustomWindowLayoutEditor {
  constructor(dev, { windowId, fileName, draft, onSaved = () => {} }) { this.dev = dev; this.windowId = windowId; this.fileName = fileName; this.draft = clone(draft); this.onSaved = onSaved; this.root = null; this.selectedId = null; this.drag = null; }
  html() { return `<div class="dev-cw-root"><div class="dev-cw-toolbar"><button type="button" class="win95-btn dev-btn" data-cw="add">＋部件</button><button type="button" class="win95-btn dev-btn" data-cw="delete">删除选中</button><button type="button" class="win95-btn dev-btn" data-cw="save">保存到内存</button><button type="button" class="win95-btn dev-btn" data-cw="download">下载 JSON</button><button type="button" class="win95-btn dev-btn" data-cw="write">写入磁盘</button><span class="dev-cw-file">${esc(this.fileName)}</span></div><div class="dev-cw-main"><aside class="dev-cw-sidebar"><h4>窗口属性</h4><label>标题<input data-cw-field="title" value="${esc(this.draft.title)}"></label><label>图标<input data-cw-field="icon" value="${esc(this.draft.icon)}"></label><label>宽度<input type="number" data-cw-field="width" value="${Number(this.draft.width)}"></label><label>高度<input type="number" data-cw-field="height" value="${Number(this.draft.height)}"></label><h4>部件列表</h4><div class="dev-cw-widget-list"></div></aside><section class="dev-cw-canvas-wrap"><div class="dev-cw-canvas" tabindex="0"></div><p class="dev-cw-help">点击选择；Ctrl/⌘ 可切换选择；拖动部件移动；双击部件打开现有蓝图编辑器。</p></section><aside class="dev-cw-inspector"><h4>部件属性</h4><div class="dev-cw-inspector-body">请选择一个部件</div></aside></div></div>`; }
  mount(root) { this.root = root; root.addEventListener("click", (e) => this.click(e)); root.addEventListener("input", (e) => this.input(e)); root.addEventListener("dblclick", (e) => this.doubleClick(e)); root.addEventListener("pointerdown", (e) => this.pointerDown(e)); this.render(); }
  render() { if (!this.root) return; const list = this.root.querySelector(".dev-cw-widget-list"); list.innerHTML = this.draft.widgets.map((w) => `<div class="dev-cw-widget-row ${w.id === this.selectedId ? "active" : ""}" data-cw-widget="${esc(w.id)}"><span>${esc(CUSTOM_WIDGET_TYPES[w.type] || w.type)}</span><small>${esc(w.id)}</small></div>`).join("") || "<p class=\"dev-cw-empty\">暂无部件</p>"; const canvas = this.root.querySelector(".dev-cw-canvas"); canvas.style.width = `${Math.max(260, Number(this.draft.width))}px`; canvas.style.height = `${Math.max(160, Number(this.draft.height))}px`; canvas.style.background = this.draft.background || "#d4d0c8"; canvas.classList.toggle("dev-cw-his-preview", this.draft.layout === "his"); canvas.innerHTML = this.draft.layout === "his" ? this.hisPreview() : this.draft.widgets.map((w) => this.preview(w)).join(""); this.renderInspector(); }
  hisPreview() { const byId = (id) => this.draft.widgets.find((w) => w.id === id); const preview = (id) => { const w = byId(id); return w ? this.preview(w) : ""; }; const panel = (id, children = "") => { const w = byId(id); if (!w) return children; const selected = w.id === this.selectedId ? " selected" : ""; return `<div class="dev-cw-widget dev-cw-his-panel${selected}" data-cw-widget="${esc(w.id)}" style="transform:translate(${Number(w.x) || 0}px,${Number(w.y) || 0}px)"><h4>${esc(w.text || (id === "diagnosis-panel" ? "诊断" : "处方"))}</h4>${children}</div>`; }; return `${preview("patient-list")}<div class="dev-cw-his-main">${preview("medical-incidents")}${preview("dialogue")}${panel("diagnosis-panel", `<div class="diagnosis-row"><label>分类: </label>${preview("diagnosis-category")}</div><div class="diagnosis-row"><label>诊断: </label>${preview("diagnosis")}</div>`)}${panel("prescription", `<div class="his-prescription-row">${preview("medicine-1")}<button type="button" disabled>+</button><button type="button" disabled>−</button></div>${preview("submit")}`)}</div>`; }
  preview(w) { const selected = w.id === this.selectedId; let body = `<span>${esc(w.text || CUSTOM_WIDGET_TYPES[w.type] || w.type)}</span>`; if (w.type === "button") body = `<button disabled>${esc(w.text || "按钮")}</button>`; if (w.type === "input") body = `<input disabled placeholder="${esc(w.placeholder || w.text || "输入")}">`; if (w.type === "textarea") body = `<textarea disabled>${esc(w.text || "")}</textarea>`; if (w.type === "select") body = `<select disabled><option>${esc(w.text || "下拉框")}</option></select>`; const flow = this.draft.layout === "his" ? ` style="transform:translate(${Number(w.x) || 0}px,${Number(w.y) || 0}px)"` : ` style="left:${Number(w.x) || 0}px;top:${Number(w.y) || 0}px;width:${Number(w.width) || 120}px;height:${Number(w.height) || 30}px"`; return `<div class="dev-cw-widget ${selected ? "selected" : ""}" data-cw-widget="${esc(w.id)}"${flow}>${body}<span class="dev-cw-widget-badge">${esc(CUSTOM_WIDGET_TYPES[w.type] || w.type)}</span></div>`; }
  renderInspector() { const body = this.root.querySelector(".dev-cw-inspector-body"); const w = this.draft.widgets.find((item) => item.id === this.selectedId); if (!w) { body.innerHTML = `<h4>窗口属性</h4><label>标题<input data-cw-field="title" value="${esc(this.draft.title)}"></label><label>图标<input data-cw-field="icon" value="${esc(this.draft.icon)}"></label><label>背景色<input data-cw-field="background" value="${esc(this.draft.background || "#d4d0c8")}"></label><div class="dev-cw-geometry">${["width", "height"].map((key) => `<label>${key}<input type="number" data-cw-field="${key}" value="${Number(this.draft[key]) || 0}"></label>`).join("")}</div><h5>窗口生命周期蓝图</h5>${["onCreate", "onDestroy"].map((event) => `<div class="dev-cw-event-row"><label>${event}<input data-cw-field="${event}" value="${esc(this.draft[event] || "")}" placeholder="蓝图 id"></label><button type="button" class="win95-btn dev-btn" data-cw-blueprint="${event}">编辑</button></div>`).join("")}<p class="dev-cw-note">未选中部件时，编辑的是窗口本身。</p>`; return; } body.innerHTML = `<label>类型<select data-cw-prop="type">${Object.entries(CUSTOM_WIDGET_TYPES).map(([id, name]) => `<option value="${id}" ${id === w.type ? "selected" : ""}>${name}</option>`).join("")}</select></label><label>部件 id<input data-cw-prop="id" value="${esc(w.id)}"></label><label>文字/标签<input data-cw-prop="text" value="${esc(w.text || "")}"></label><label>占位文字<input data-cw-prop="placeholder" value="${esc(w.placeholder || "")}"></label><div class="dev-cw-geometry">${["x", "y", "width", "height"].map((key) => `<label>${key}<input type="number" data-cw-prop="${key}" value="${Number(w[key]) || 0}"></label>`).join("")}</div><h5>事件蓝图</h5>${["onClick", "onChange", "onSubmit", "onSelect"].map((event) => `<div class="dev-cw-event-row"><label>${event}<input data-cw-prop="${event}" value="${esc(w[event] || "")}" placeholder="蓝图 id"></label><button type="button" class="win95-btn dev-btn" data-cw-blueprint="${event}">编辑</button></div>`).join("")}<p class="dev-cw-note">“编辑”会打开现有蓝图编辑器；窗口校验和蓝图校验相互独立。</p>`; }
  select(id, additive) { if (additive && this.selectedId === id) this.selectedId = null; else this.selectedId = id; this.render(); }
  click(e) { const action = e.target.closest("[data-cw]")?.dataset.cw; if (action === "add") { this.draft.widgets.push(newWidget()); this.selectedId = this.draft.widgets.at(-1).id; this.render(); } else if (action === "delete") { this.draft.widgets = this.draft.widgets.filter((w) => w.id !== this.selectedId); this.selectedId = null; this.render(); } else if (action === "save") this.save(); else if (action === "download") this.download(); else if (action === "write") this.write(); const target = e.target.closest("[data-cw-widget]"); if (target) { this.select(target.dataset.cwWidget, e.ctrlKey || e.metaKey); e.stopPropagation(); } else if (e.target.closest(".dev-cw-canvas")) { this.selectedId = null; this.render(); } const blueprint = e.target.closest("[data-cw-blueprint]"); if (blueprint) this.openBlueprint(blueprint.dataset.cwBlueprint); }
  input(e) { const field = e.target.dataset.cwField; if (field) { this.draft[field] = ["width", "height"].includes(field) ? Number(e.target.value) : e.target.value; if (["width", "height"].includes(field)) this.render(); return; } const prop = e.target.dataset.cwProp; const w = this.draft.widgets.find((item) => item.id === this.selectedId); if (!prop || !w) return; if (prop === "id") { const oldId = w.id; w.id = e.target.value; this.selectedId = w.id; this.draft.widgets.forEach((item) => Object.keys(item).forEach((key) => { if (["onCreate", "onDestroy", "onClick", "onChange", "onSubmit", "onSelect"].includes(key) && item[key] === oldId) item[key] = w.id; })); } else w[prop] = ["x", "y", "width", "height"].includes(prop) ? Number(e.target.value) : e.target.value; if (e.target.matches("select") || ["x", "y", "width", "height", "type"].includes(prop)) this.render(); }
  pointerDown(e) { const target = e.target.closest(".dev-cw-widget"); if (!target || e.target.closest("input,button,select,textarea")) return; const w = this.draft.widgets.find((item) => item.id === target.dataset.cwWidget); if (!w) return; this.select(w.id, e.ctrlKey || e.metaKey); this.drag = { x: e.clientX, y: e.clientY, ox: Number(w.x) || 0, oy: Number(w.y) || 0, widget: w }; const move = (event) => { if (!this.drag) return; w.x = Math.max(0, this.drag.ox + event.clientX - this.drag.x); w.y = Math.max(0, this.drag.oy + event.clientY - this.drag.y); const el = this.root.querySelector(`.dev-cw-widget[data-cw-widget="${CSS.escape(w.id)}"]`); if (el) { if (this.draft.layout === "his") el.style.transform = `translate(${w.x}px,${w.y}px)`; else { el.style.left = `${w.x}px`; el.style.top = `${w.y}px`; } } }; const up = () => { this.drag = null; document.removeEventListener("pointermove", move); document.removeEventListener("pointerup", up); }; document.addEventListener("pointermove", move); document.addEventListener("pointerup", up); }
  doubleClick(e) { const target = e.target.closest("[data-cw-widget]"); if (!target) return; this.select(target.dataset.cwWidget, false); const w = this.draft.widgets.find((item) => item.id === this.selectedId); if (w?.onClick) this.openBlueprint("onClick"); else this.dev.setStatus("该部件未绑定 onClick 蓝图，请在右侧填写蓝图 id。", true); }
  async openBlueprint(eventName) { const w = this.draft.widgets.find((item) => item.id === this.selectedId); const target = w || this.draft; const blueprintId = target[eventName]; if (!blueprintId) return this.dev.setStatus(`请先填写 ${eventName} 蓝图 id。`, true); const raw = this.draft.blueprints?.[blueprintId] || createCustomEventBlueprint(); const project = { version: 2, totalDays: 1, customVars: [], activities: { [this.windowId]: { displayName: this.draft.title, entries: [{ id: blueprintId, type: "other", name: blueprintId, blueprint: clone(raw) }] } }, events: {}, endings: {} }; const host = document.createElement("div"); const child = new DevDialogueEditorTab(this.dev, { workspace: false, project, initialCtx: { type: "activity", id: this.windowId, entryIndex: 0 }, embeddedScope: { title: `${this.draft.title} · ${w?.id || "窗口"} · ${eventName}`, onSave: (blueprint) => { this.draft.blueprints[blueprintId] = clone(blueprint); this.dev.docs.set(this.fileName, clone(this.draft)); this.dev.setStatus(`${blueprintId} 已保存回窗口文件内存。`); } } }); const win = windowManager.createWindow({ title: `蓝图编辑器 · ${blueprintId}`, icon: "🧩", width: Math.max(700, window.innerWidth - 30), height: Math.max(500, window.innerHeight - 30), x: 0, y: 0, content: host, onClose: () => child.unmount() }); win.el?.classList.add("dev-blueprint-window"); host.innerHTML = child.html(); child.mount(host.querySelector(".dev-de-root")); }
  async save() { const result = validateCustomWindow(this.draft); if (!result.ok) { this.dev.setStatus(`窗口校验失败：${result.errors.join("；")}`, true); return false; } this.draft = result.value; this.dev.docs.set(this.fileName, clone(this.draft)); this.onSaved(this.draft); this.dev.setStatus(`${this.fileName} 已保存到内存。`); return true; }
  download() { if (!this.save()) return false; this.dev.downloadFile(this.fileName, this.draft); return true; }
  async write() { if (!await this.save()) return false; return this.dev.writeToDisk(this.fileName, this.draft); }
}

export class DevCustomWindowManager {
  constructor(dev) { this.dev = dev; this.root = null; this.apps = []; }
  html() { return `<div class="dev-cwm-root"><div class="dev-cwm-toolbar"><button type="button" class="win95-btn dev-btn" data-cwm="add">＋新建窗口</button><button type="button" class="win95-btn dev-btn" data-cwm="reload">刷新列表</button><button type="button" class="win95-btn dev-btn" data-cwm="save">保存列表到内存</button><button type="button" class="win95-btn dev-btn" data-cwm="download">下载列表</button><button type="button" class="win95-btn dev-btn" data-cwm="write">写入列表</button><span>applist.json</span></div><p class="dev-cwm-help">双击窗口条目打开布局编辑器；蓝图编辑通过现有蓝图编辑器完成。</p><div class="dev-cwm-list"></div></div>`; }
  async mount(root) { this.root = root; root.innerHTML = this.html(); root.addEventListener("click", (e) => this.handle(e)); root.addEventListener("dblclick", (e) => this.handle(e)); await this.reload(); }
  async reload() { try { const data = await this.dev.loadDoc("applist.json"); this.apps = Array.isArray(data) ? data : data.apps || []; this.render(); this.dev.setStatus(`已加载 ${this.apps.length} 个自定义窗口。`); } catch (error) { this.apps = []; this.render(); this.dev.setStatus(`无法加载 applist.json：${error.message}`, true); } }
  render() { this.root.querySelector(".dev-cwm-list").innerHTML = this.apps.map((app) => `<div class="dev-cwm-row" data-cwm-id="${esc(app.id)}"><span class="dev-cwm-icon">${esc(app.icon || "🗔")}</span><strong>${esc(app.title || app.id)}</strong><small>${esc(app.file || `app_${app.id}.json`)}</small><button type="button" class="win95-btn dev-btn" data-cwm="run" data-cwm-id="${esc(app.id)}">运行</button><button type="button" class="win95-btn dev-btn" data-cwm="download" data-cwm-id="${esc(app.id)}">下载</button><button type="button" class="win95-btn dev-btn" data-cwm="delete" data-cwm-id="${esc(app.id)}">−</button></div>`).join("") || "<p class=\"dev-cwm-empty\">暂无自定义窗口，点击“＋新建窗口”开始。</p>"; }
  async handle(e) { const action = e.target.closest("[data-cwm]")?.dataset.cwm; const id = e.target.closest("[data-cwm-id]")?.dataset.cwmId; if (action === "reload") return this.reload(); if (action === "add") return this.add(); if (action === "save") { this.dev.docs.set("applist.json", clone(this.apps)); return this.dev.setStatus("applist.json 已保存到内存。"); } if (action === "write") { this.dev.docs.set("applist.json", clone(this.apps)); return this.dev.writeToDisk("applist.json", this.apps); } if (action === "download") { if (!id) return this.dev.downloadFile("applist.json", this.apps); const app = this.apps.find((item) => item.id === id); if (app) this.dev.downloadFile(app.file || `app_${id}.json`, await this.dev.loadDoc(app.file || `app_${id}.json`)); return; } if (action === "run") return launchCustomWindowApp(id); if (action === "delete") { this.apps = this.apps.filter((app) => app.id !== id); this.dev.docs.set("applist.json", clone(this.apps)); this.render(); return; } if (e.type === "dblclick" && id) return this.open(id); }
  async add() { let n = 1; while (this.apps.some((app) => app.id === `custom_${n}`)) n += 1; const id = `custom_${n}`; const app = { id, title: "新窗口", icon: "🗔", file: `app_${id}.json` }; const draft = createCustomWindowDraft(id); this.apps.push(app); this.dev.docs.set("applist.json", this.apps); this.dev.docs.set(app.file, draft); this.render(); this.open(id, draft); this.dev.setStatus(`已创建 ${app.file} 草稿；请分别保存列表和窗口文件。`); }
  async open(id, supplied = null) { const app = this.apps.find((item) => item.id === id); if (!app) return; let draft = supplied; if (!draft) draft = await this.dev.loadDoc(app.file || `app_${id}.json`); const host = document.createElement("div"); const editor = new DevCustomWindowLayoutEditor(this.dev, { windowId: id, fileName: app.file || `app_${id}.json`, draft, onSaved: (value) => { app.title = value.title; app.icon = value.icon; this.dev.docs.set("applist.json", this.apps); this.render(); } }); const win = windowManager.createWindow({ title: `窗口编辑器 · ${app.title || id}`, icon: app.icon || "🗔", width: 1000, height: 680, content: host, onClose: () => {} }); win.el?.classList.add("dev-custom-window-editor"); host.innerHTML = editor.html(); editor.mount(host.querySelector(".dev-cw-root")); }
}
// DEV-TOOLS:END
