// DEV-TOOLS:START
import { WindowRuntime } from "../core/WindowRuntime.js";
import { validateWindowDefinition } from "../core/WindowSchema.js";

const clone = (value) => structuredClone(value);
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const TYPES = ["label", "button", "textInput", "textarea", "select", "checkbox", "image", "list", "table", "progress", "spacer"];

export class CustomWindowEditor {
  constructor({ definition, onChange = () => {}, runtime = new WindowRuntime() } = {}) { this.definition = clone(definition || { id: "window", title: "窗口", root: { type: "container", children: [] } }); this.definition.width ||= this.definition.geometry?.width || 520; this.definition.height ||= this.definition.geometry?.height || 360; if (!this.definition.root) this.definition.root = { type: "container", children: (this.definition.content?.paragraphs || []).map((text, index) => ({ id: `paragraph_${index + 1}`, type: "label", text, x: 16, y: 16 + index * 32, width: 460, height: 24 })) }; this.onChange = onChange; this.runtime = runtime; this.root = null; this.selectedPath = []; }
  mount(root) { this.root = root; this.render(); }
  selected() { let node = this.definition.root; for (const index of this.selectedPath) node = node?.children?.[index]; return node; }
  render() {
    this.root.replaceChildren();
    const shell = document.createElement("div"); shell.className = "ng-wysiwyg-editor"; shell.innerHTML = `<header class="ng-wysiwyg-toolbar"><strong>WYSIWYG 窗口管理器</strong><button data-cw="add">＋部件</button><button data-cw="delete">删除选中</button><button data-cw="validate">校验</button><button data-cw="save">保存</button></header><main class="ng-wysiwyg-main"><aside class="ng-wysiwyg-tree" data-cw-tree></aside><section class="ng-wysiwyg-preview"><div class="ng-wysiwyg-surface" data-cw-preview></div></section><aside class="ng-wysiwyg-inspector" data-cw-inspector></aside></main><footer data-cw-status>实时预览使用 WindowRuntime</footer>`;
    this.root.append(shell); this.renderTree(); this.renderPreview(); this.renderInspector();
    shell.onclick = (event) => { const action = event.target.closest("[data-cw]")?.dataset.cw; if (action === "add") this.add(); if (action === "delete") this.remove(); if (action === "validate") this.validate(); if (action === "save") this.save(); const row = event.target.closest("[data-cw-path]"); if (row) { this.selectedPath = row.dataset.cwPath ? row.dataset.cwPath.split(".").map(Number) : []; this.renderTree(); this.renderPreview(); this.renderInspector(); } };
    shell.oninput = (event) => { const field = event.target.dataset.cwField; const node = this.selected(); if (!field || !node) return; node[field] = ["x", "y", "width", "height"].includes(field) ? Number(event.target.value) : event.target.value; this.renderPreview(); };
  }
  renderTree() { const tree = this.root.querySelector("[data-cw-tree]"); const walk = (node, path, depth) => `<button class="ng-wysiwyg-tree-row${JSON.stringify(path) === JSON.stringify(this.selectedPath) ? " selected" : ""}" data-cw-path="${path.join(".")}" style="padding-left:${8 + depth * 14}px">${node.type} · ${node.id || "未命名"}</button>${(node.children || []).map((child, index) => walk(child, [...path, index], depth + 1)).join("")}`; tree.innerHTML = walk(this.definition.root, [], 0); }
  renderPreview() { const preview = this.root.querySelector("[data-cw-preview]"); preview.style.width = `${Number(this.definition.width) || 520}px`; preview.style.height = `${Number(this.definition.height) || 360}px`; this.runtime.render(this.definition, preview); preview.querySelectorAll("[data-widget-id]").forEach((el) => { const path = this.findPath(el.dataset.widgetId); el.classList.toggle("selected", JSON.stringify(path) === JSON.stringify(this.selectedPath)); el.onclick = (event) => { event.stopPropagation(); this.selectedPath = path; this.renderTree(); this.renderPreview(); this.renderInspector(); }; }); }
  findPath(id) { let result = null; const visit = (node, path) => { if (node.id === id) result = path; (node.children || []).forEach((child, index) => visit(child, [...path, index])); }; visit(this.definition.root, []); return result || []; }
  renderInspector() { const node = this.selected(); const body = this.root.querySelector("[data-cw-inspector]"); if (!node) { body.innerHTML = "<h3>窗口</h3><p>选择左侧部件编辑属性。</p>"; return; } body.innerHTML = `<h3>部件属性</h3><label>ID<input data-cw-field="id" value="${esc(node.id)}"></label><label>类型<select data-cw-field="type">${TYPES.map((type) => `<option ${type === node.type ? "selected" : ""}>${type}</option>`).join("")}</select></label><label>文字<input data-cw-field="text" value="${esc(node.text)}"></label><div class="ng-wysiwyg-grid">${["x", "y", "width", "height"].map((key) => `<label>${key}<input type="number" data-cw-field="${key}" value="${Number(node[key]) || 0}"></label>`).join("")}</div>`; }
  add() { const parent = this.selected() || this.definition.root; parent.children ||= []; parent.children.push({ id: `widget_${Date.now().toString(36)}`, type: "label", text: "新部件", x: 20, y: 20, width: 120, height: 28 }); this.selectedPath = [...this.selectedPath, parent.children.length - 1]; this.render(); }
  remove() { if (!this.selectedPath.length) return; const parentPath = this.selectedPath.slice(0, -1); const parent = parentPath.reduce((node, index) => node.children[index], this.definition.root); parent.children.splice(this.selectedPath.at(-1), 1); this.selectedPath = parentPath; this.render(); }
  validate() { const result = validateWindowDefinition(this.definition); this.status(result.valid ? "窗口定义校验通过。" : result.errors.join("；"), !result.valid); return result; }
  save() { const result = this.validate(); if (result.valid) this.onChange(clone(this.definition)); }
  status(text, error = false) { const el = this.root.querySelector("[data-cw-status]"); el.textContent = text; el.classList.toggle("error", error); }
}
// DEV-TOOLS:END
