import { EventBus } from "../core/EventBus.js";
import { createDefaultNodeRegistry } from "../core/ActivityNodeRegistry.js";
import { ActivityValidator } from "../core/ActivityValidator.js";
import { ActivityDefinitionStore } from "../core/ActivityDefinitionStore.js";
import { ActivityQueueRegistry } from "../core/ActivityQueueRegistry.js";
import { ActivityExecutionService } from "../core/ActivityExecutionService.js";
import { PublicVariableManager } from "../core/PublicVariableManager.js";
const bus = new EventBus(); const vars = new PublicVariableManager(bus); vars.register({ id: 0, name: "probe", type: "smallInteger", defaultValue: 0, min: 0, max: 255 });
const nodes = createDefaultNodeRegistry(); const validator = new ActivityValidator(nodes); const definition = { id: "probe", version: 1, entry: "start", nodes: [{ id: "start", type: "start" }, { id: "set", type: "setVariable", data: { variableId: 0, value: 7 } }, { id: "end", type: "end" }], connections: [{ id: "a", from: { node: "start", port: "next" }, to: { node: "set", port: "in" } }, { id: "b", from: { node: "set", port: "next" }, to: { node: "end", port: "in" } }] };
if (!validator.validate(definition).valid) throw new Error("valid definition rejected"); const invalid = validator.validate({ ...definition, nodes: [{ id: "start", type: "missing" }, ...definition.nodes.slice(1)] }); if (invalid.valid) throw new Error("invalid node accepted");
const definitions = new ActivityDefinitionStore(); definitions.register(definition); const queues = new ActivityQueueRegistry(bus); queues.register({ queueId: "main" }); const execution = new ActivityExecutionService({ definitions, queues, nodes, eventBus: bus, effects: { setVariable: (node) => vars.set(node.data.variableId, node.data.value) } }); const instance = execution.create({ definitionId: "probe" }); execution.start(instance);
if (vars.get(0) !== 7 || instance.status !== "resolved" || queues.get("main").entries.length !== 1) throw new Error("activity execution failed"); console.log("PASS: Activity validation, queue identity and setVariable execution");
