export class DataStructureManager {
  constructor(eventBus) { this.eventBus = eventBus; this.definitions = new Map(); this.databases = new Map(); }
  register(definition) { if (!definition?.id || this.definitions.has(definition.id)) throw new Error(`Invalid or duplicate structure: ${definition?.id}`); const fields = definition.fields || []; const ids = new Set(); for (const field of fields) { if (!field.id || ids.has(field.id)) throw new Error(`Duplicate field: ${field.id}`); ids.add(field.id); } this.definitions.set(definition.id, structuredClone(definition)); }
  createDatabase(databaseId, recordType) { if (!this.definitions.has(recordType) || this.databases.has(databaseId)) throw new Error(`Invalid database: ${databaseId}`); this.databases.set(databaseId, { databaseId, recordType, records: [] }); }
  insert(databaseId, record) { const db = this.databases.get(databaseId); if (!db) throw new Error(`Unknown database: ${databaseId}`); const value = structuredClone(record); if (!value.id || db.records.some((item) => item.id === value.id)) throw new Error(`Duplicate record: ${value.id}`); db.records.push(value); this.eventBus?.emit("database:changed", { databaseId, action: "insert", id: value.id }); return value; }
  find(databaseId, predicate = () => true) { return (this.databases.get(databaseId)?.records || []).filter(predicate).map((record) => structuredClone(record)); }
  update(databaseId, id, patch) { const record = this.databases.get(databaseId)?.records.find((item) => item.id === id); if (!record) throw new Error(`Unknown record: ${id}`); Object.assign(record, structuredClone(patch)); this.eventBus?.emit("database:changed", { databaseId, action: "update", id }); return structuredClone(record); }
  remove(databaseId, id) { const db = this.databases.get(databaseId); const index = db?.records.findIndex((item) => item.id === id); if (index < 0) throw new Error(`Unknown record: ${id}`); db.records.splice(index, 1); this.eventBus?.emit("database:changed", { databaseId, action: "delete", id }); }
  snapshot() { return { definitions: Object.fromEntries(this.definitions), databases: Object.fromEntries(this.databases) }; }
  restore(snapshot = {}) { this.definitions = new Map(Object.entries(snapshot.definitions || {})); this.databases = new Map(Object.entries(snapshot.databases || {})); }
}
